sudo: required

language: node_js


env:
  - NODE_ENV=travis

notifications:
  webhooks: https://files-aopiaslhxw.now.sh
node_js: lts/*

install:
  - yarn install

script:
  - commitlint-travis
  - npm run lint
  - npm run test
