language: node_js
node_js: lts/*

stages:
  - Lint & Tests

jobs:
  include:
    - stage: Lint & Tests
      name: Lint commit messages
      script: commitlint-travis
    - script: yarn lint
      name: Lint JavaScript
    - script: yarn test
      name: Tests
